service: aws-node-http-api-project
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: '20201221'
  region: us-east-1
  iam:
      role:
          statements:
            - Effect: Allow
              Action:
                - dynamodb:PutItem
                - dynamodb:UpdateItem
                - dynamodb:GetItem
                - dynamodb:Scan
                - dynamodb:DeleteItem
              Resource:
                - arn:aws:dynamodb:us-east-1:383745556589:table/MyFirstTable

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get

  insertItem:
    handler: src/insert.handler
    events:
      - http:
          path: /item
          method: post

  fetchItems:
    handler: src/getAll.handler
    events:
      - http:
          path: /item
          method: get

  fetchItem:
    handler: src/getOne.handler
    events:
      - http:
          path: /item/{id}
          method: get

  updateItem:
    handler: src/update.handler
    events:
      - http:
          path: /item
          method: put

  deleteItem:
    handler: src/delete.handler
    events:
      - http:
          path: /item
          method: delete

resources:
  Resources:
    ItemTable:
      Type: AWS::DynamoDB::Table
      Properties:
          TableName: MyFirstTable
          BillingMode: PAY_PER_REQUEST
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
